delay: 0.15
input:
  LPD8:
    144+36+<50:
      exec: say 'Soft touch'
    144+36+<50%:
      exec: say 'Soft percentage'
    144+36+>50%:
      exec: say 'Hard percentage'
    144+40:
      exec: say 'Hello world'
