delay: 0.15
debug: false
input:
  LPD8:
    144+39:
      open: /Applications/Google Chrome.app
    144+36:
      open: /Applications/MacVim.app
    144+38:
      open: /Applications/iTerm.app
    144+43:
      open: /Applications/Google Chrome.app
